image:
  pullPolicy: IfNotPresent
  pullSecrets: aws-secret
  backend:
    repository: 587447957359.dkr.ecr.us-east-1.amazonaws.com/portfolio-backend
    tag: "1.0.10"
  mongodb:
    repository: 587447957359.dkr.ecr.us-east-1.amazonaws.com/portfolio-mongodb
    tag: "1.0.3"


backend:
  replicas: 1
  service:
    type: NodePort
    port: 5000
    name: backend
  env:
    mongo_uri: mongodb-0.mongodb-headless

mongodb:
  replicas: 3
  service:
    port: 27017
    name: mongodb-headless

